version: '3'
name: fasz
services:
  python_flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    tty: true
    restart: unless-stopped